name: Test action using test data

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-get-property:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3.2.0
      - name: Get property
        id: get-property
        uses: ./
        with:
          file: test-data/basic.properties
          property: foo
      - name: Verify correct value
        if: steps.get-property.outputs.value != 'bar'
        run: |
          exit 1
  test-no-newline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3.2.0
      - name: Get property
        id: get-property
        uses: ./
        with:
          file: test-data/no-newline.properties
          property: foo
      - name: Verify correct value
        if: steps.get-property.outputs.value != 'bar'
        run: |
          exit 1
  test-multiline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3.2.0
      - name: Get property
        id: get-property
        uses: ./
        with:
          file: test-data/basic.properties
          property: multiline
      - name: Verify correct value
        if: steps.get-property.outputs.value != 'foobar'
        run: |
          exit 1
  test-duplicate-key:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3.2.0
      - name: Get property
        id: get-property
        uses: ./
        with:
          file: test-data/basic.properties
          property: duplicateKey
      - name: Verify correct value
        if: steps.get-property.outputs.value != 'second'
        run: |
          exit 1
  test-escaping:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3.2.0
      - name: Get property
        id: get-property
        uses: ./
        with:
          file: test-data/basic.properties
          property: escaping
      - name: Verify correct value
        if: steps.get-property.outputs.value != 'foo\bar'
        run: |
          exit 1
  test-colon:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3.2.0
      - name: Get property
        id: get-property
        uses: ./
        with:
          file: test-data/basic.properties
          property: colon
      - name: Verify correct value
        if: steps.get-property.outputs.value != 'colon'
        run: |
          exit 1
